name: CI


on:
  pull_request:
    branches:
      - master
      - release/*

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install modules
        run: npm install

      - name: Run tests
        run: npm run test
      
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_REPO_UPLOAD_TOKEN }}
          files: coverage/lcov.info
          name: codecov-skyflow-node
          verbose: true
      
      - name: Build
        run: npm run build